// ─── DevControlPanel Styles ──────────────────────────────────────────────────

export const SIDEBAR_WIDTH = 300;
export const SIDEBAR_COLLAPSED_WIDTH = 28;

export const s = {
  panel: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    width: `${SIDEBAR_WIDTH}px`,
    height: 'calc(100vh - 180px)',
    display: 'flex' as const,
    flexDirection: 'column' as const,
    background: '#141414',
    borderRight: '1px solid #2a2a2a',
    color: '#ddd',
    fontFamily: '"Courier New", monospace',
    fontSize: '11px',
    zIndex: 9999,
    boxShadow: '4px 0 24px rgba(0,0,0,0.5)',
    userSelect: 'none' as const,
    pointerEvents: 'auto' as const,
    transition: 'transform 0.25s ease',
  },
  header: {
    background: '#0d0d0d',
    padding: '7px 10px',
    borderBottom: '1px solid #2a2a2a',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    cursor: 'pointer',
    flexShrink: 0,
  },
  title: {
    margin: 0,
    fontSize: '10px',
    color: '#555',
    letterSpacing: '2px',
    textTransform: 'uppercase' as const,
  },
  tabNav: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '2px',
    padding: '5px',
    background: '#111',
    borderBottom: '1px solid #222',
  },
  section: {
    padding: '9px 10px',
    borderBottom: '1px solid #1c1c1c',
  },
  h3: {
    margin: '0 0 7px 0',
    fontSize: '9px',
    color: '#777',
    textTransform: 'uppercase' as const,
    letterSpacing: '1px',
  },
  row: { marginBottom: '7px' },
  label: {
    display: 'block' as const,
    color: '#aaa',
    fontSize: '11px',
    marginBottom: '2px',
  },
  checkLabel: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '6px',
    color: '#aaa',
    fontSize: '11px',
    cursor: 'pointer',
  },
  range: {
    width: '100%',
    margin: '3px 0',
    accentColor: '#3b82f6',
  },
  select: {
    width: '100%',
    background: '#222',
    color: '#ddd',
    border: '1px solid #3a3a3a',
    borderRadius: '3px',
    padding: '3px 5px',
    fontSize: '11px',
  },
  btnSm: {
    background: '#1e1e1e',
    color: '#bbb',
    border: '1px solid #3a3a3a',
    borderRadius: '3px',
    cursor: 'pointer',
    padding: '3px 7px',
    fontSize: '10px',
  },
  btnPrimary: {
    background: '#3b82f6',
    color: '#fff',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    padding: '5px 10px',
    fontSize: '11px',
    width: '100%',
    marginBottom: '4px',
  },
  btnDanger: {
    background: '#ef4444',
    color: '#fff',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    padding: '5px 10px',
    fontSize: '11px',
    width: '100%',
  },
  btnReset: {
    background: 'transparent',
    color: '#555',
    border: '1px solid #2a2a2a',
    borderRadius: '3px',
    cursor: 'pointer',
    padding: '3px 8px',
    fontSize: '10px',
    marginTop: '4px',
  },
  colorInput: {
    width: '34px',
    height: '20px',
    border: '1px solid #3a3a3a',
    borderRadius: '3px',
    cursor: 'pointer',
    padding: 0,
    verticalAlign: 'middle',
    marginLeft: '6px',
  },
  presetGrid: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '3px',
  },
  statGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '2px',
    marginBottom: '5px',
    fontSize: '10px',
  },
  statLabel: { color: '#555' },
  statVal: { color: '#4ade80', textAlign: 'right' as const },
  progressWrap: {
    height: '4px',
    background: '#2a2a2a',
    borderRadius: '2px',
    overflow: 'hidden' as const,
    margin: '3px 0',
  },
  table: { width: '100%', borderCollapse: 'collapse' as const, fontSize: '10px' },
  th: { textAlign: 'left' as const, padding: '3px 4px', borderBottom: '1px solid #2a2a2a', color: '#555' },
  td: { padding: '2px 4px', borderBottom: '1px solid #1a1a1a', color: '#999' },
  flexRow: { display: 'flex', flexWrap: 'wrap' as const, gap: '3px', marginTop: '3px' },
  infoBox: {
    background: '#0d0d0d',
    borderRadius: '3px',
    padding: '5px 7px',
    fontSize: '10px',
    color: '#444',
    lineHeight: 1.5,
    marginTop: '4px',
  },
};

export const tabBtnSt = (active: boolean) => ({
  ...s.btnSm,
  background: active ? '#3b82f6' : '#181818',
  color: active ? '#fff' : '#555',
  border: `1px solid ${active ? '#3b82f6' : '#2a2a2a'}`,
  padding: '2px 7px',
  fontSize: '10px',
});

export const presetBtnSt = (active: boolean) => ({
  ...s.btnSm,
  background: active ? '#3b82f6' : '#202020',
  color: active ? '#fff' : '#888',
  border: `1px solid ${active ? '#3b82f6' : '#3a3a3a'}`,
});
